workflows:
  ios-workflow:
    name: ios_workflow
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "co.beamproject.beammobile"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(Z0FBQUFBQmdYZkNmaVpoamFxQ2h0THBZWXpoS3hlVU5mZVVBVktmZ3ZxM2ZsOEhvU1pVcThzbzAyV1lXd195Q0YzYWNHZDN1ajBKdlpuLU5Ma0FhbDgzc0hRb2hGX2VYdG95UTdHcm95a2pQM1hpYWFDbFNYUU16cTh6dnRhWGxmckpPNHllbFhNeU0=)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(Z0FBQUFBQmdYZkZJQW9hZFFyM1hQTmZTYm9TZUUyNG92eFIzekFuR2YzWFkzSF9Vd0lrRFdHOW5OMDQ2U1FXUXpZLUVlVWNodUV3aWZUN3RQME1BSHhpd09BOVMzdEhjcmc9PQ==)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmdYZkhnWGVObVN6MUh1T0d2UTdKYTRXRC1KWEJUMUJuTU5xbjFLTjhSTE9PcmJiTVRuSkVJNG9hQTc5ZU0yR3Q5Z1pPZE1UWE5WV3lVN1VsNzRUeHEyeEdia1hieGVieWVkV0RNRy1pbjQ5cms3QWM2WkMwMzN4WFJzczZpWGNIR3JUYW5yZVZBSWRzcWlBdFNPUVdFNVEtZ3BDQzI5cnAyeFFRb3ZjMS1jSllWSWdYNUFMVU5Wc0tQbXpCSTQzdncyX1oyUXNmS21neGYwZmtJMy1UVGx6V2szcjVvUmtrR3J2UmJLUVRiUzUtVF9lT194RDI3N2FiV2FKQ3VNSGZzSXlEOUhlcGxyZ25FR3lWc1NWSmVuT1hKUEtMODdNcl9ReGEtRGY2U0NnZVVMU1JkNXEzLUVjUHlvYl9iUEx6T2dzREs0SlJGdm5nQnQtZTVoekFXLU11UjUyS3NRREp4M2VFcEtaczVlRmQtbVBlOWRBQzJSVDc3aEt5aXI5UWgwYk9wV2l4TFRTdWhuaUtUS3VybmhweXY2Z2pxQng4MElhM1psSW1FSWJCbnZVND0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmdYZkpueGI2QWJoNE1aLUsxMk93N2pxdTZKeFZZQTFSVXFKcGxENW5aTEZOYXN6WVM4WjRWUFljekFva1ZlVzFyLW9OMGJmTFpQaFZmaDFmYnJtMGdLWFE4T0trQ1BzT2hDWDVoMU1xZjRPQW56dGlDNzRDQUNJU2MwNkw4cF9RWUdQR3JDTDJMZ1B1WmVnYXU2X2VxTE5TSlJQUXU2UVJON3ozZTVzNTY3UU10OTVjeXk4VGlOVWdqZEthMmFZblRxV2JmX3VqY3IxNEw2VlhkeDFRbWNqTFFxZlk1YkV2dTU4MmNxbnR4R2pWdXlETjBLUkRrenRkTFRvSmZvTnRJUHBwOEotLXd3dVMzeFo5LVl4ZnJRUnZmeThCVW9KMmRUTHdmRFNLNjB3by04RWRkTk9ObW12cm9XbUtNUDdHYV9pRzFudk5WdFpqampQYUhpcHpjODVwcWpHZ1ZmMmMtcEVlNjJsZ282X0xQWWJxajBuY3FmcnlIVFpNZmZvTmtoRHF0ejFiVlNTOGJNMXh3SDlya0tMNUNuVGFmazd0b0FqZnU0d0wxNU9pb0o0bVRKZEVaWVNiLVRjRmNZbG1RX21zTFBJck1GTXFwbi0zVmdoOXdvTTRWcS03dE1qRExDckE5UkJoNlh1YzNYWU9NcmxrNFRNSlBYLS1LRVRtd3NLZGVsVGNjdndUQ2V2WTd4TWswdUZ2Sl9PZzVCeWpObl90ZW5DdWdiVGk0ZTVEX2M1Vjgtb2FwUkxwWW1EN3dhbE8wY0RTUG9wTHpSdWMyaEdEX3RRV0pjOWxENW40UksxVGZVOWJjaFQ5cGdBZnpEZUZKSXFDTThlU0QyY0d6TFZWZl9DQ3pXelhwMzl2U01VLWlkSlh0RlBxMkswNFp0RzNLQm1ybUluSXYxTmtvTFVZWFhiSkRtTTI1Vjh3aUlIVjA2am9GNHZ4bHRXTjZyQWFzVi1GcHJYZUx6N0ptdk9YUTV2ZXNDdk9ocUp5eUx4ekRycWd4bno3bFVMWTFJVUxuZVo3YmNKN0NGdmNRT2tWTm5QTFpQSjN1ZUNxbTlsaGhtempWLUlMTjBLWlRoTjdTWmZHRUUycE14TlB6eFNpa1hzR21oMVNiSmI1WGNwWnNZZXFwSWo4OTdtWEtFRmZCTF9tVlhvVUVOOVBBdUZWX0hfRTZ3QTVwcElHWjZTVW9hVTdMbVgzTDgxMU0yT2pTNkVkOVUyN3N3ejhpdGkxVDRndEVSZFF1N1FoakJpeHd5UVJaN1o5RFlQTUZVNjl3Qm1TZDBwaDdJRW5jV3R1UkVsbXpIbW1ZVFZfTlN3eGxhampXTnYwZ1F6Z3VqOTc4MTIwVWhrMUlURDc0dFVxTEQyaU1TMnVpb2hYLXNDZ2tzOUJqOVhqNG55Slk1VkJ4aVRLRDR0WWdIUHYtb2FfV3pjdmhiMEdiZjE5UFhVcWwweF9sNjBmZ1NmeE00REo3T0RBUjFXUXJvc1VEOTdUOW1jOEViSTl2UElhRTl1Z2tJQkVTOHU3NTFOaldwbGVEbjhSMUkydU1pNmhFRXNxeEdsTnhQOUtTZ1BqSkljUl80M1B3cUJjZjBqckYwel9DRENFSzdGM1UxaVNmZG9OZTY3RVFiYVVVRFNPaUZvajFSeTBvMzU0VlIyd2pZSy1aczlyeWdjZmRQV1otalg5MHBraHhWMU1nNHZ6WTFZV2pkR3BkMGpDWEhnU2ZpTndnTTlZeXdvVFFKaTNJV3RMelVfZHMzOC03VTFtNnJJZVBFZ3FCRGJhNFRDc0YtZkpEWE5nckgwUk1abkJRaFJYVVBoaEZRVHQ1NVdHbFJEWXdVQmk1RnBibnFPLVFqRVQtaXJiaGVURUFjYms4ekpwdnYxa1FxOXduSTQycUtwOHRjRW41ZTUxZ25JWFZiNU9CLVFHWWxNa0JwQkNNTjYxcGR6TEFzcnd2ejUtaElnUll0MzBnWUNTRU5pektmcHd0UEczaVFKLXUxLVI4ZF9YY09pVWsxcXB6cF9QQ184Ukg5WUlIVEQ4aDlESVhCNUpKeS1ZekRraF83Ty05cl9tRkJGbEhjck5RQnhlRVJkcTM5X2gtNDNWQlJwYUU1UENyZXhnUTVmcE5xdUdUV0dSV0JYRjM1X2pvVkNxS3lmb240bHpJUnllY1FQa3ZkVUJFanVYREVLWmxJcUJ4T2xSNDFqcmdNeDBXZjVETWlLeExZQ1NDdDVqWUVMUk9DY3NXSnF1dC1OaHZPTnhLMUM3OWFDQUdpODA3cWhkZnVvR1dJeU42aHB0WnpfNGpmR1ZwMktndmtfcURiaHJEYlM0N3JpWF9IOXE2Vi16NldkdEdQa1cxRzlPUklzcG41bnpTREhPMXppTzBuRm9YZWpmQk1STGpncXIxbGFuUlZPNnRtV0stTGlxUEFENlhJUHpYak9kdUNFSGU4ZmZwUmZpal8yeWZjY2cyVXJoYlJvNGVncnR6eWxDU3FLMG1KaXZmOHN3SERGUlNZMXNZbnk3am9XemUxUmdweFFQMFQ0Z29fbmVDZ3pDWFNKMXpJZ0Zhd0RKa01WY0VwYzQ0VllIRXJnTGpWRS1MMjdnUGFFSWozZ3JCTlNIOEhINU5LMXZaZXRkbUhIQnhxMkhUMTM4ZEM4aGZVOFJJamZGZnZDME0wMjNraFNEX1RKNkFCWDllelRrT3VHUHYySl9PbGdsRGY4a0hNNWJuZURSMmRmS3F6TnpBdENRaXFMWUJKdnB4eWlMa09GZFlIVGRTYVI1YkFoS1FFckVUalFIeWtjRHRrUUp5OWFHUGFMbkdUUXY5bVFpNUtkTjlKQW1wSm1rYmppNXdFNnNxODdkYzRkbHYyVDBQeThONUpUaWNpTjRfZjdvUllIN3NOd01fczl5ZlhEN0JPRXZNbGNwLW11YTMxUE50aW9fWDl4d1IwLXBQakxGazg5UUlEeEg4ZmR1NUt4alpacWw4dXBiRnMta0p6eVRYbmVhUUR4YXgyMGZJeXpPX1FpdzYySVhuME40M2FtMS1pV3IyZ2N1akVkQWs1bnFoTzQtZzV5cHhUaWZs)
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_DEVELOPMENT \
            --create
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build Flutter
        script: flutter build ios
#      - name: Increment build number
#        script: agvtool new-version -all $(($BUILD_NUMBER +1))
      - name: Build ipa for distribution
        script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
#      email:
#        recipients:
#          - balasz.mateusz@gmail.com
#        notify:
#          success: false
#          failure: false
      app_store_connect:
        apple_id: balasz.mateusz@gmail.com
        password: Encrypted(Z0FBQUFBQmdYZlNPYnpIT25SWmhYSTB1TUFXY0llaFo0UjUtT2RXOC1KWXNJZFZDWkxXbGlOdTV4V3ZycVFvUmI2aXZycDZvMnhKbjhYX3hEVEg5NnNCcnFJSFNzN1I5U1piQkRzbWE4bUx2R0VVVnJSNlBvSkE9)
