# This file is required to work around a build_runner issue.
# See https://github.com/dart-lang/build/issues/2835#issuecomment-703528119
name: test
description: A new Flutter application.
version: 1.0.0

dependencies:

dev_dependencies: